### ISSUE TITLE
"Severe internal error. Please contact your administrator"

### ISSUE THREAD

**Issue by MEGAGRIMREAPER69** [turt2live/DumbAuction#11]
It was working one day and then when i started the server back up form it, we cant start an auction with /auction start or /auc start. I deleted the plugin from the server and re-downloaded it and it still happens. I have no idea what is going on.

**Comment by turt2live** [comment]
There would have to be an error in the server log, please provide that

**Comment by MEGAGRIMREAPER69** [comment]
03.01 11:57:03 [Server] WARN at com.turt2live.dumbauction.command.AuctionCommandHandler.auctionStartCommand(AuctionCommandHandler.java:517)

**Comment by turt2live** [comment]
The entire error please. The single line given is not enough to look into the problem

**Comment by MEGAGRIMREAPER69** [comment]
How do i get to that? I'm new with some of this.

**Comment by turt2live** [comment]
You have to open the log file and copy the entire error.

**Comment by MEGAGRIMREAPER69** [comment]
[Server thread/INFO]: MEGAGRIMREAPER69 issued server command: /auction start 32 100 100
[00:41:59] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[00:41:59] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:41:59] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[00:41:59] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:41:59] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[00:41:59] [Server thread/WARN]: 	at com.turt2live.dumbauction.command.AuctionCommandHandler.onCommand(AuctionCommandHandler.java:166)
[00:41:59] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:41:59] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180)
[00:41:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServer.java:701)
[00:41:59] [Server thread/WARN]: 	at net.minecraft.server.

This is what i found

**Comment by MEGAGRIMREAPER69** [comment]
[00:46:35] [Server thread/INFO]: MEGAGRIMREAPER69 issued server command: /auction start 32 100 100
[00:46:35] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[00:46:35] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:46:35] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[00:46:35] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:46:35] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[00:46:35] [Server thread/WARN]: 	at com.turt2live.dumbauction.command.AuctionCommandHandler.onCommand(AuctionCommandHandler.java:166)
[00:46:35] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:46:35] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180)
[00:46:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R3.CraftServer.dispatchCommand(CraftServer.java:701)
[00:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R3.PlayerConnection.handleCommand(PlayerConnection.java:956)
[00:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:817)
[00:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R3.PacketPlayInChat.a(PacketPlayInChat.java:28)
[00:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R3.PacketPlayInChat.handle(PacketPlayInChat.java:47)
[00:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:157)
[00:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R3.ServerConnection.c(SourceFile:134)
[00:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:667)
[00:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260)
[00:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558)
[00:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469)
[00:46:35] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
[00:46:35] [Server thread/WARN]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.milkbowl.vault.item.Items
[00:46:35] [Server thread/WARN]: 	at com.turt2live.dumbauction.command.AuctionCommandHandler.auctionStartCommand(AuctionCommandHandler.java:517)

theres the whole thing

**Comment by turt2live** [comment]
Looks like you don't have Vault installed

**Comment by MEGAGRIMREAPER69** [comment]
i did install vault, unless theres an updates for vault

**Comment by MEGAGRIMREAPER69** [comment]
There is an update for it, but the update only runs with 1.8+ and we're running 1.7.9

**Comment by turt2live** [comment]
In that case it probably had an error during startup. Please use the version of vault applicable to your server version.
